GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer 1654651

{
  "title": "Adding a fifth blog with user",
  "author": "Harry Potter",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5
}

###

DELETE http://localhost:3003/api/blogs/6398e10ce0bbcbe6495c700c

###
PUT http://localhost:3003/api/blogs/6
Content-Type: application/json

{
  "likes": 444
}