GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvbiIsImlkIjoiNjM5OGUwMWZjY2JjZDIxOGM4OTg0ZDExIiwiaWF0IjoxNjcxNDY1Mzg3LCJleHAiOjE2NzE0Njg5ODd9.c_zKvxX1YT6hJmN70zQY5tr1TmzTqoN_3jc1CBRBli4

{
  "title": "Blog authentication header check",
  "author": "Harry Potter",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5
}

###

DELETE http://localhost:3003/api/blogs/639760e52cee1fc1bbb34840
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvbiIsImlkIjoiNjM5OGUwMWZjY2JjZDIxOGM4OTg0ZDExIiwiaWF0IjoxNjcxNDY1Mzg3LCJleHAiOjE2NzE0Njg5ODd9.c_zKvxX1YT6hJmN70zQY5tr1TmzTqoN_3jc1CBRBli4


###
PUT http://localhost:3003/api/blogs/6
Content-Type: application/json

{
  "likes": 444
}

###
POST http://localhost:3003/api/blogs/6398e12ce0bbcbe6495c7013/comments
Content-Type: application/json

{
  "comments": "This is the second comment"
}